// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbFD12O1hWmGldg3DkOYbpA7SdAeUw7OU',
    appId: '1:50796510527:web:76bb56e3c9b7a26ed8e78a',
    messagingSenderId: '50796510527',
    projectId: 'food-recipe-944de',
    authDomain: 'food-recipe-944de.firebaseapp.com',
    storageBucket: 'food-recipe-944de.appspot.com',
    measurementId: 'G-7ENPL39SFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFApCdUfW5rskSMjwpTpCY7T4JowRBapk',
    appId: '1:50796510527:android:44c474c9f9564742d8e78a',
    messagingSenderId: '50796510527',
    projectId: 'food-recipe-944de',
    storageBucket: 'food-recipe-944de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtYOvVVQSZCBQe3hxlkod28B3eOhx3bV8',
    appId: '1:50796510527:ios:d90c7d7b8aa53ea1d8e78a',
    messagingSenderId: '50796510527',
    projectId: 'food-recipe-944de',
    storageBucket: 'food-recipe-944de.appspot.com',
    iosBundleId: 'com.example.rasoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtYOvVVQSZCBQe3hxlkod28B3eOhx3bV8',
    appId: '1:50796510527:ios:d90c7d7b8aa53ea1d8e78a',
    messagingSenderId: '50796510527',
    projectId: 'food-recipe-944de',
    storageBucket: 'food-recipe-944de.appspot.com',
    iosBundleId: 'com.example.rasoi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbFD12O1hWmGldg3DkOYbpA7SdAeUw7OU',
    appId: '1:50796510527:web:7f8d775400c2eb7fd8e78a',
    messagingSenderId: '50796510527',
    projectId: 'food-recipe-944de',
    authDomain: 'food-recipe-944de.firebaseapp.com',
    storageBucket: 'food-recipe-944de.appspot.com',
    measurementId: 'G-H6Z536FYYX',
  );

}